[SEARCH]
GOOGLE_SEARCH_ENGINE_ID=""
GOOGLE_MAPS_KEY=""
BING_API_KEY=""
YELP_API_KEY=""

[LLM]
OPENAI_API_KEY=""

[LOGGING]
LOGGING_PATH="logs"
LOGGING="true"
DEBUG_LOGGING="true"

[API_ENDPOINTS]

[APP_CONFIG]
PRIMARY_CONTENT_SIZE=800
SECONDARY_CONTENT_SIZE=450
CONTENT_PER_LLM_CALL=4
MAX_SITES_PER_QUERY=12
MAX_LLM_CALLS=15
WEB_SCRAPING_TIMEOUT=25500



